version: '3.4'

services:
  app:
    image: node:8.12.0-alpine
    command: npm run start
    tty: true
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - "8080:8080"
    restart: always

  mongodb:
    image: mongo:3.6.7-stretch
